name: depreciation-app-frontend

services:
  frontend:
    build:
      context: .
      dockerfile: ./docker-files/Dockerfile
      target: nginx-build
    # env_file: "./docker-files/.env"
    profiles: ["frontend-prod"]
    networks:
      - depreciation-app_front-tier
    ports:
      - 8080:80
    

  frontendev:
    build:
      context: .
      dockerfile: ./docker-files/Dockerfile
      target: client-dev
    env_file: "./docker-files/.env"
    profiles: ["frontend-dev"]
    networks:
      - depreciation-app_front-tier
    ports:
      - 5173:4174
    volumes:
      - ./src:/app/src

networks:
  depreciation-app_front-tier:
    external: true
  

