- name: My first play
  hosts: all
  become: yes

  tasks:
 

  - name: Ping my hosts
    ansible.builtin.ping:

  - name: Print message
    ansible.builtin.debug:
      msg: Hello world

  -  name: install apache2
     apt:
        name: apache2
        update_cache: yes
        state: latest

  - name: Copy build folder
    ansible.builtin.copy:
      src: /var/jenkins_home/workspace/depreciation_pipeline_frontend/dist/
      dest: /var/www/html/
      force: true
      mode: '0644'

  - name: Copy node modules
    ansible.posix.synchronize:
        src: /var/jenkins_home/workspace/depreciation_pipeline_frontend/node_modules
        dest: /var/www/html 
        force: true  
        mode: '0644'
      # owner: ubuntu
      # group: ubuntu
    #   remote_src: yes
    # become: true 
    # become_user: root 
    #   # directory_mode: '700'     
